version: '3.8'

services:
  wallet-service:
    build:
      context: ./wallet-service
    ports:
      - "8081:8081"
    volumes:
      - ./wallet-service:/app
    working_dir: /app
    command: go run cmd/main.go

  asset-service:
    build:
      context: ./asset-service
    ports:
      - "8082:8082"
    volumes:
      - ./asset-service:/app
    working_dir: /app
    command: go run cmd/main.go

  scheduled-service:
    build:
      context: ./scheduled-service
    ports:
      - "8083:8083"
    volumes:
      - ./scheduled-service:/app
    working_dir: /app
    command: go run cmd/main.go